server:
    port: 8082

spring:
    kafka:
        bootstrap-servers: localhost:9092
        properties:
            schema.registry.url: http://localhost:8081
        consumer:
            group-id: async-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            properties:
                specific.avro.reader: true # desserializa para a classe gerada a partir do .avsc
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

app:
    kafka:
        topic: mensagens-topic
