plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.0.20' apply false
    id 'org.jetbrains.kotlin.plugin.spring' version '2.0.20' apply false
    id 'org.springframework.boot' version '3.5.5' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'org.jlleitschuh.gradle.ktlint' version '12.1.1' apply false
}

group = 'com.example' // grupo de pacotes do projeto
version = '0.0.1-SNAPSHOT' // manual

allprojects {
    repositories {
        mavenCentral() // fonte de pacotes (libs)
    }
}


subprojects {

    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'org.jetbrains.kotlin.plugin.spring'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.jlleitschuh.gradle.ktlint'

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(21))
        }
    }

    kotlin { jvmToolchain(21) }

    // desabilitado por padrão; módulos com @SpringBootApplication reativam em seu próprio build.gradle
    bootJar { enabled = false } // TODO pesquisar sobre bootJar e jar no Spring Boot
    jar { enabled = true }

    // usado em tempo de compilação para gerar código-fonte a partir de arquivos
    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'org.springframework.boot:spring-boot-starter-validation'
        implementation 'org.jetbrains.kotlin:kotlin-reflect'
        implementation 'org.jetbrains.kotlin:kotlin-stdlib'
        // modules
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    test {
        useJUnitPlatform()
    }

}