plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.24'
    id 'org.jetbrains.kotlin.plugin.spring' version '1.9.24'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'org.jlleitschuh.gradle.ktlint' version '12.1.1'
}

group = 'com.example' // grupo de pacotes do projeto
version = '0.0.1-SNAPSHOT' // manual

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

kotlin { jvmToolchain(21) }

repositories {
    mavenCentral() // fonte de pacotes (libs)
}

// usado em tempo de compilação para gerar código-fonte a partir de arquivos
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}

tasks.jar {
    enabled = true
}

tasks.bootJar {
    enabled = true
}

// dependencias x plugins
// test (task)

// estrutura do build, jvm, jar
// próximo passo: criar módulos, 3 (core, api-build, async-build) no qual todos enxergam core.
